add_newline = true
format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$rust\
$line_break\
$character
"""

[directory]
truncate_to_repo = false

[line_break]
disabled = false

[character]
error_symbol = "[✗](bold red) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'cyan'

